### ISSUE TITLE
Not connecting on server

### ISSUE THREAD

**Issue by olaven** [JimCronqvist/action-ssh#3]
Hello, 

Thanks for making this project! 
Unfortunately, I am struggeling to get it to work .

My logging just ends with 
```
# Commands:
echo "$SECRET_VAR_1 <- is var 1"
echo "$SECRET_VAR_2 <- is var 2"


Connecting to ***@***:***...
```

Then the action fails without reporting anything 😕 
Unfortunately, I cannot share the run itself, as it is not yet a public project.

My `yml`-file looks like this: 
```yml
- name: Execute SSH commmands on remote server
  uses: JimCronqvist/action-ssh@master
  env: 
    SECRET_VAR_1: ${{ secrets.SECRET_VAR }}
    SECRET_VAR_2: ${{ secrets.SECRET_VAR }}
  with:
    hosts: "${{ secrets.USERNAME}}@${{ secrets.HOST }}:${{ secrets.SSH_PORT }}"
    privateKey: ${{ secrets.SSH_KEY }}
    command: |
      echo "$SECRET_VAR_1 <- is var 1"
      echo "$SECRET_VAR_2 <- is var 2"
``` 

(Actuan env-variabes replaced with SECRET_VAR)

Thanks for any help and have a nice day!

**Comment by muffintoad** [comment]
Same for me @JimCronqvist

**Comment by almostengr** [comment]
Same here... this does not work. 

What I have in mine is 

```yml
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy code to production
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: '${{ secrets.LOGIN_WITH_PORT }}'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: ls
```

**Comment by ganshiqingyuan** [comment]
same

**Comment by thekendog** [comment]
Same issue.  Guess this doesn't work anymore.

**Comment by ian-whitestone** [comment]
I wonder if it has to do with specifying the port. Action works fine for me when using an SSH server with default port 22. after changing the port (lets say to 8080), i tried to update my host in the ssh action so its like the example provided in the README, `user@host_ip:8080`, and then i start getting the error. if you try and run this SSH command locally it also doesn't work, you have to do `ssh user@host_ip -p 8080`

**Comment by ian-whitestone** [comment]
Yeah i think that was it. I just forked the repo: https://github.com/ian-whitestone/action-ssh

```yaml
steps:
    - name: Test SSH connection
      uses: ian-whitestone/action-ssh@master
      with:
        debug: false
        hosts: '${{ secrets.MAC_C2_USERNAME }}@${{ secrets.MAC_C2_HOST }}'
        port: ${{ secrets.MAC_C2_PORT }}
        privateKey: ${{ secrets.MAC_C2_SSH_KEY }}
        command: |
          echo "Connection successful!"
```

This is all i changed: https://github.com/ian-whitestone/action-ssh/commit/db7057fd8ef8a1a1e07dfe2f2668bbd682b77499

Note, if you're trying to use this with multiple hosts, it would use the same `port` for all hosts.
